apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: healthpro
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://auth-service-db:5432/health_pro"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "create"
  SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "true"
  SPRING_SQL_INIT_MODE: "always"
  SERVER_PORT: "8080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clinic-service-config
  namespace: healthpro
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://clinic-service-db:5432/health_pro"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "create"
  SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "true"
  SPRING_SQL_INIT_MODE: "always"
  SERVER_PORT: "8081"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: schedule-service-config
  namespace: healthpro
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://schedule-service-db:5432/health_pro"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "create"
  SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "true"
  SPRING_SQL_INIT_MODE: "always"
  SERVER_PORT: "8082"
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: api-gateway-config
    namespace: healthpro
data:
    AUTH_SERVICE_URL: "http://auth-service:8080"
    SERVER_PORT: "4004"
