apiVersion: v1
kind: Secret
metadata:
  name: healthpro-secrets
  namespace: healthpro
type: Opaque
stringData:
  DB_NAME: "health_pro"
  DB_USERNAME: "root"
  DB_PASSWORD: "password"
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: password
  JWT_SECRET: "VGhpcy1pcy1hLXNlY3JldC1rZXktZm9yLUpXVC0yNTYtYml0IQ=="