spring:
  application:
    name: schedule-service
#  datasource:
#    url: jdbc:postgresql://localhost:5002/health_pro
#    username: root
#    password: password
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    defer-datasource-initialization: true
#
#  sql:
#    init:
#      mode: always
#      data-locations: ""
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      group-id: schedule-service
      auto-commit-interval: 1000
#      bootstrap-servers: localhost:9094
    listener:
      ack-mode: record
#server:
#  port: 8082
logging:
  level:
    org:
      apache:
        kafka: DEBUG
      springframework:
        kafka: DEBUG
