apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinic-service
  namespace: healthpro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clinic-service
  template:
    metadata:
      labels:
        app: clinic-service
    spec:
      containers:
        - name: clinic-service
          image: healthpro/clinic-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: clinic-service-config
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: healthpro-secrets
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: healthpro-secrets
                  key: SPRING_DATASOURCE_PASSWORD