apiVersion: v1
kind: Service
metadata:
  name: clinic-service
  namespace: healthpro
spec:
  selector:
    app: clinic-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP