apiVersion: v1
kind: Service
metadata:
  name: schedule-service
  namespace: healthpro
spec:
  selector:
    app: schedule-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP